package com.example.thymeleaf.dao;

import com.example.thymeleaf.model.Brother;
import com.example.thymeleaf.model.BrotherExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BrotherMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_brother
     *
     * @mbggenerated Mon Jul 23 11:10:52 CST 2018
     */
    int countByExample(BrotherExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_brother
     *
     * @mbggenerated Mon Jul 23 11:10:52 CST 2018
     */
    int deleteByExample(BrotherExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_brother
     *
     * @mbggenerated Mon Jul 23 11:10:52 CST 2018
     */
    int deleteByPrimaryKey(Integer brotherId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_brother
     *
     * @mbggenerated Mon Jul 23 11:10:52 CST 2018
     */
    int insert(Brother record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_brother
     *
     * @mbggenerated Mon Jul 23 11:10:52 CST 2018
     */
    int insertSelective(Brother record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_brother
     *
     * @mbggenerated Mon Jul 23 11:10:52 CST 2018
     */
    List<Brother> selectByExample(BrotherExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_brother
     *
     * @mbggenerated Mon Jul 23 11:10:52 CST 2018
     */
    Brother selectByPrimaryKey(Integer brotherId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_brother
     *
     * @mbggenerated Mon Jul 23 11:10:52 CST 2018
     */
    int updateByExampleSelective(@Param("record") Brother record, @Param("example") BrotherExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_brother
     *
     * @mbggenerated Mon Jul 23 11:10:52 CST 2018
     */
    int updateByExample(@Param("record") Brother record, @Param("example") BrotherExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_brother
     *
     * @mbggenerated Mon Jul 23 11:10:52 CST 2018
     */
    int updateByPrimaryKeySelective(Brother record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_brother
     *
     * @mbggenerated Mon Jul 23 11:10:52 CST 2018
     */
    int updateByPrimaryKey(Brother record);
}