package com.example.thymeleaf.dao;

import com.example.thymeleaf.model.BrotherChapter;
import com.example.thymeleaf.model.BrotherChapterExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BrotherChapterMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_brother_chapter
     *
     * @mbggenerated Mon Jul 23 11:10:52 CST 2018
     */
    int countByExample(BrotherChapterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_brother_chapter
     *
     * @mbggenerated Mon Jul 23 11:10:52 CST 2018
     */
    int deleteByExample(BrotherChapterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_brother_chapter
     *
     * @mbggenerated Mon Jul 23 11:10:52 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_brother_chapter
     *
     * @mbggenerated Mon Jul 23 11:10:52 CST 2018
     */
    int insert(BrotherChapter record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_brother_chapter
     *
     * @mbggenerated Mon Jul 23 11:10:52 CST 2018
     */
    int insertSelective(BrotherChapter record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_brother_chapter
     *
     * @mbggenerated Mon Jul 23 11:10:52 CST 2018
     */
    List<BrotherChapter> selectByExample(BrotherChapterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_brother_chapter
     *
     * @mbggenerated Mon Jul 23 11:10:52 CST 2018
     */
    BrotherChapter selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_brother_chapter
     *
     * @mbggenerated Mon Jul 23 11:10:52 CST 2018
     */
    int updateByExampleSelective(@Param("record") BrotherChapter record, @Param("example") BrotherChapterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_brother_chapter
     *
     * @mbggenerated Mon Jul 23 11:10:52 CST 2018
     */
    int updateByExample(@Param("record") BrotherChapter record, @Param("example") BrotherChapterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_brother_chapter
     *
     * @mbggenerated Mon Jul 23 11:10:52 CST 2018
     */
    int updateByPrimaryKeySelective(BrotherChapter record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_brother_chapter
     *
     * @mbggenerated Mon Jul 23 11:10:52 CST 2018
     */
    int updateByPrimaryKey(BrotherChapter record);
}