package com.example.thymeleaf.dao;

import com.example.thymeleaf.model.DomainCssSelector;
import com.example.thymeleaf.model.DomainCssSelectorExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DomainCssSelectorMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_domain_css_selector
     *
     * @mbggenerated Fri Nov 30 18:44:53 CST 2018
     */
    int countByExample(DomainCssSelectorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_domain_css_selector
     *
     * @mbggenerated Fri Nov 30 18:44:53 CST 2018
     */
    int deleteByExample(DomainCssSelectorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_domain_css_selector
     *
     * @mbggenerated Fri Nov 30 18:44:53 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_domain_css_selector
     *
     * @mbggenerated Fri Nov 30 18:44:53 CST 2018
     */
    int insert(DomainCssSelector record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_domain_css_selector
     *
     * @mbggenerated Fri Nov 30 18:44:53 CST 2018
     */
    int insertSelective(DomainCssSelector record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_domain_css_selector
     *
     * @mbggenerated Fri Nov 30 18:44:53 CST 2018
     */
    List<DomainCssSelector> selectByExample(DomainCssSelectorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_domain_css_selector
     *
     * @mbggenerated Fri Nov 30 18:44:53 CST 2018
     */
    DomainCssSelector selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_domain_css_selector
     *
     * @mbggenerated Fri Nov 30 18:44:53 CST 2018
     */
    int updateByExampleSelective(@Param("record") DomainCssSelector record, @Param("example") DomainCssSelectorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_domain_css_selector
     *
     * @mbggenerated Fri Nov 30 18:44:53 CST 2018
     */
    int updateByExample(@Param("record") DomainCssSelector record, @Param("example") DomainCssSelectorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_domain_css_selector
     *
     * @mbggenerated Fri Nov 30 18:44:53 CST 2018
     */
    int updateByPrimaryKeySelective(DomainCssSelector record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_domain_css_selector
     *
     * @mbggenerated Fri Nov 30 18:44:53 CST 2018
     */
    int updateByPrimaryKey(DomainCssSelector record);
}