package com.example.thymeleaf.dao;

import com.example.thymeleaf.model.NearText;
import com.example.thymeleaf.model.NearTextExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface NearTextMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_near_text
     *
     * @mbggenerated Fri Dec 14 13:50:13 CST 2018
     */
    int countByExample(NearTextExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_near_text
     *
     * @mbggenerated Fri Dec 14 13:50:13 CST 2018
     */
    int deleteByExample(NearTextExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_near_text
     *
     * @mbggenerated Fri Dec 14 13:50:13 CST 2018
     */
    int deleteByPrimaryKey(Integer nearId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_near_text
     *
     * @mbggenerated Fri Dec 14 13:50:13 CST 2018
     */
    int insert(NearText record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_near_text
     *
     * @mbggenerated Fri Dec 14 13:50:13 CST 2018
     */
    int insertSelective(NearText record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_near_text
     *
     * @mbggenerated Fri Dec 14 13:50:13 CST 2018
     */
    List<NearText> selectByExample(NearTextExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_near_text
     *
     * @mbggenerated Fri Dec 14 13:50:13 CST 2018
     */
    NearText selectByPrimaryKey(Integer nearId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_near_text
     *
     * @mbggenerated Fri Dec 14 13:50:13 CST 2018
     */
    int updateByExampleSelective(@Param("record") NearText record, @Param("example") NearTextExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_near_text
     *
     * @mbggenerated Fri Dec 14 13:50:13 CST 2018
     */
    int updateByExample(@Param("record") NearText record, @Param("example") NearTextExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_near_text
     *
     * @mbggenerated Fri Dec 14 13:50:13 CST 2018
     */
    int updateByPrimaryKeySelective(NearText record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_near_text
     *
     * @mbggenerated Fri Dec 14 13:50:13 CST 2018
     */
    int updateByPrimaryKey(NearText record);
}