package com.example.thymeleaf.dao;

import com.example.thymeleaf.model.ScheduleTask;
import com.example.thymeleaf.model.ScheduleTaskExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ScheduleTaskMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_schedule_task
     *
     * @mbggenerated Mon Jul 23 11:10:52 CST 2018
     */
    int countByExample(ScheduleTaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_schedule_task
     *
     * @mbggenerated Mon Jul 23 11:10:52 CST 2018
     */
    int deleteByExample(ScheduleTaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_schedule_task
     *
     * @mbggenerated Mon Jul 23 11:10:52 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_schedule_task
     *
     * @mbggenerated Mon Jul 23 11:10:52 CST 2018
     */
    int insert(ScheduleTask record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_schedule_task
     *
     * @mbggenerated Mon Jul 23 11:10:52 CST 2018
     */
    int insertSelective(ScheduleTask record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_schedule_task
     *
     * @mbggenerated Mon Jul 23 11:10:52 CST 2018
     */
    List<ScheduleTask> selectByExample(ScheduleTaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_schedule_task
     *
     * @mbggenerated Mon Jul 23 11:10:52 CST 2018
     */
    ScheduleTask selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_schedule_task
     *
     * @mbggenerated Mon Jul 23 11:10:52 CST 2018
     */
    int updateByExampleSelective(@Param("record") ScheduleTask record, @Param("example") ScheduleTaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_schedule_task
     *
     * @mbggenerated Mon Jul 23 11:10:52 CST 2018
     */
    int updateByExample(@Param("record") ScheduleTask record, @Param("example") ScheduleTaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_schedule_task
     *
     * @mbggenerated Mon Jul 23 11:10:52 CST 2018
     */
    int updateByPrimaryKeySelective(ScheduleTask record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_schedule_task
     *
     * @mbggenerated Mon Jul 23 11:10:52 CST 2018
     */
    int updateByPrimaryKey(ScheduleTask record);
}