package com.example.thymeleaf.model;

public class Article {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_article.id
     *
     * @mbggenerated Mon Jul 23 11:10:52 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_article.comment
     *
     * @mbggenerated Mon Jul 23 11:10:52 CST 2018
     */
    private String comment;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_article.title
     *
     * @mbggenerated Mon Jul 23 11:10:52 CST 2018
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_article.list_url
     *
     * @mbggenerated Mon Jul 23 11:10:52 CST 2018
     */
    private String listUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_article.info_url
     *
     * @mbggenerated Mon Jul 23 11:10:52 CST 2018
     */
    private String infoUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_article.seed_id
     *
     * @mbggenerated Mon Jul 23 11:10:52 CST 2018
     */
    private Integer seedId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_article.category_id
     *
     * @mbggenerated Mon Jul 23 11:10:52 CST 2018
     */
    private Integer categoryId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_article.status
     *
     * @mbggenerated Mon Jul 23 11:10:52 CST 2018
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_article.click_times
     *
     * @mbggenerated Mon Jul 23 11:10:52 CST 2018
     */
    private Integer clickTimes;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_article.img
     *
     * @mbggenerated Mon Jul 23 11:10:52 CST 2018
     */
    private String img;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_article.author
     *
     * @mbggenerated Mon Jul 23 11:10:52 CST 2018
     */
    private String author;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_article.modify_date
     *
     * @mbggenerated Mon Jul 23 11:10:52 CST 2018
     */
    private String modifyDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_article.brother_state
     *
     * @mbggenerated Mon Jul 23 11:10:52 CST 2018
     */
    private String brotherState;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_article.id
     *
     * @return the value of t_article.id
     *
     * @mbggenerated Mon Jul 23 11:10:52 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_article.id
     *
     * @param id the value for t_article.id
     *
     * @mbggenerated Mon Jul 23 11:10:52 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_article.comment
     *
     * @return the value of t_article.comment
     *
     * @mbggenerated Mon Jul 23 11:10:52 CST 2018
     */
    public String getComment() {
        return comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_article.comment
     *
     * @param comment the value for t_article.comment
     *
     * @mbggenerated Mon Jul 23 11:10:52 CST 2018
     */
    public void setComment(String comment) {
        this.comment = comment == null ? null : comment.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_article.title
     *
     * @return the value of t_article.title
     *
     * @mbggenerated Mon Jul 23 11:10:52 CST 2018
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_article.title
     *
     * @param title the value for t_article.title
     *
     * @mbggenerated Mon Jul 23 11:10:52 CST 2018
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_article.list_url
     *
     * @return the value of t_article.list_url
     *
     * @mbggenerated Mon Jul 23 11:10:52 CST 2018
     */
    public String getListUrl() {
        return listUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_article.list_url
     *
     * @param listUrl the value for t_article.list_url
     *
     * @mbggenerated Mon Jul 23 11:10:52 CST 2018
     */
    public void setListUrl(String listUrl) {
        this.listUrl = listUrl == null ? null : listUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_article.info_url
     *
     * @return the value of t_article.info_url
     *
     * @mbggenerated Mon Jul 23 11:10:52 CST 2018
     */
    public String getInfoUrl() {
        return infoUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_article.info_url
     *
     * @param infoUrl the value for t_article.info_url
     *
     * @mbggenerated Mon Jul 23 11:10:52 CST 2018
     */
    public void setInfoUrl(String infoUrl) {
        this.infoUrl = infoUrl == null ? null : infoUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_article.seed_id
     *
     * @return the value of t_article.seed_id
     *
     * @mbggenerated Mon Jul 23 11:10:52 CST 2018
     */
    public Integer getSeedId() {
        return seedId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_article.seed_id
     *
     * @param seedId the value for t_article.seed_id
     *
     * @mbggenerated Mon Jul 23 11:10:52 CST 2018
     */
    public void setSeedId(Integer seedId) {
        this.seedId = seedId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_article.category_id
     *
     * @return the value of t_article.category_id
     *
     * @mbggenerated Mon Jul 23 11:10:52 CST 2018
     */
    public Integer getCategoryId() {
        return categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_article.category_id
     *
     * @param categoryId the value for t_article.category_id
     *
     * @mbggenerated Mon Jul 23 11:10:52 CST 2018
     */
    public void setCategoryId(Integer categoryId) {
        this.categoryId = categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_article.status
     *
     * @return the value of t_article.status
     *
     * @mbggenerated Mon Jul 23 11:10:52 CST 2018
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_article.status
     *
     * @param status the value for t_article.status
     *
     * @mbggenerated Mon Jul 23 11:10:52 CST 2018
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_article.click_times
     *
     * @return the value of t_article.click_times
     *
     * @mbggenerated Mon Jul 23 11:10:52 CST 2018
     */
    public Integer getClickTimes() {
        return clickTimes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_article.click_times
     *
     * @param clickTimes the value for t_article.click_times
     *
     * @mbggenerated Mon Jul 23 11:10:52 CST 2018
     */
    public void setClickTimes(Integer clickTimes) {
        this.clickTimes = clickTimes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_article.img
     *
     * @return the value of t_article.img
     *
     * @mbggenerated Mon Jul 23 11:10:52 CST 2018
     */
    public String getImg() {
        return img;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_article.img
     *
     * @param img the value for t_article.img
     *
     * @mbggenerated Mon Jul 23 11:10:52 CST 2018
     */
    public void setImg(String img) {
        this.img = img == null ? null : img.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_article.author
     *
     * @return the value of t_article.author
     *
     * @mbggenerated Mon Jul 23 11:10:52 CST 2018
     */
    public String getAuthor() {
        return author;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_article.author
     *
     * @param author the value for t_article.author
     *
     * @mbggenerated Mon Jul 23 11:10:52 CST 2018
     */
    public void setAuthor(String author) {
        this.author = author == null ? null : author.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_article.modify_date
     *
     * @return the value of t_article.modify_date
     *
     * @mbggenerated Mon Jul 23 11:10:52 CST 2018
     */
    public String getModifyDate() {
        return modifyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_article.modify_date
     *
     * @param modifyDate the value for t_article.modify_date
     *
     * @mbggenerated Mon Jul 23 11:10:52 CST 2018
     */
    public void setModifyDate(String modifyDate) {
        this.modifyDate = modifyDate == null ? null : modifyDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_article.brother_state
     *
     * @return the value of t_article.brother_state
     *
     * @mbggenerated Mon Jul 23 11:10:52 CST 2018
     */
    public String getBrotherState() {
        return brotherState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_article.brother_state
     *
     * @param brotherState the value for t_article.brother_state
     *
     * @mbggenerated Mon Jul 23 11:10:52 CST 2018
     */
    public void setBrotherState(String brotherState) {
        this.brotherState = brotherState == null ? null : brotherState.trim();
    }
}