package com.example.thymeleaf.model;

import java.util.Date;

public class BrotherChapter {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_brother_chapter.id
     *
     * @mbggenerated Mon Jul 23 11:10:52 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_brother_chapter.brother_id
     *
     * @mbggenerated Mon Jul 23 11:10:52 CST 2018
     */
    private Integer brotherId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_brother_chapter.seq_id
     *
     * @mbggenerated Mon Jul 23 11:10:52 CST 2018
     */
    private Integer seqId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_brother_chapter.title
     *
     * @mbggenerated Mon Jul 23 11:10:52 CST 2018
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_brother_chapter.url
     *
     * @mbggenerated Mon Jul 23 11:10:52 CST 2018
     */
    private String url;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_brother_chapter.local_url
     *
     * @mbggenerated Mon Jul 23 11:10:52 CST 2018
     */
    private String localUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_brother_chapter.chapter_id
     *
     * @mbggenerated Mon Jul 23 11:10:52 CST 2018
     */
    private Integer chapterId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_brother_chapter.collect_flag
     *
     * @mbggenerated Mon Jul 23 11:10:52 CST 2018
     */
    private Integer collectFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_brother_chapter.update_time
     *
     * @mbggenerated Mon Jul 23 11:10:52 CST 2018
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_brother_chapter.id
     *
     * @return the value of t_brother_chapter.id
     *
     * @mbggenerated Mon Jul 23 11:10:52 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_brother_chapter.id
     *
     * @param id the value for t_brother_chapter.id
     *
     * @mbggenerated Mon Jul 23 11:10:52 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_brother_chapter.brother_id
     *
     * @return the value of t_brother_chapter.brother_id
     *
     * @mbggenerated Mon Jul 23 11:10:52 CST 2018
     */
    public Integer getBrotherId() {
        return brotherId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_brother_chapter.brother_id
     *
     * @param brotherId the value for t_brother_chapter.brother_id
     *
     * @mbggenerated Mon Jul 23 11:10:52 CST 2018
     */
    public void setBrotherId(Integer brotherId) {
        this.brotherId = brotherId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_brother_chapter.seq_id
     *
     * @return the value of t_brother_chapter.seq_id
     *
     * @mbggenerated Mon Jul 23 11:10:52 CST 2018
     */
    public Integer getSeqId() {
        return seqId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_brother_chapter.seq_id
     *
     * @param seqId the value for t_brother_chapter.seq_id
     *
     * @mbggenerated Mon Jul 23 11:10:52 CST 2018
     */
    public void setSeqId(Integer seqId) {
        this.seqId = seqId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_brother_chapter.title
     *
     * @return the value of t_brother_chapter.title
     *
     * @mbggenerated Mon Jul 23 11:10:52 CST 2018
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_brother_chapter.title
     *
     * @param title the value for t_brother_chapter.title
     *
     * @mbggenerated Mon Jul 23 11:10:52 CST 2018
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_brother_chapter.url
     *
     * @return the value of t_brother_chapter.url
     *
     * @mbggenerated Mon Jul 23 11:10:52 CST 2018
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_brother_chapter.url
     *
     * @param url the value for t_brother_chapter.url
     *
     * @mbggenerated Mon Jul 23 11:10:52 CST 2018
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_brother_chapter.local_url
     *
     * @return the value of t_brother_chapter.local_url
     *
     * @mbggenerated Mon Jul 23 11:10:52 CST 2018
     */
    public String getLocalUrl() {
        return localUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_brother_chapter.local_url
     *
     * @param localUrl the value for t_brother_chapter.local_url
     *
     * @mbggenerated Mon Jul 23 11:10:52 CST 2018
     */
    public void setLocalUrl(String localUrl) {
        this.localUrl = localUrl == null ? null : localUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_brother_chapter.chapter_id
     *
     * @return the value of t_brother_chapter.chapter_id
     *
     * @mbggenerated Mon Jul 23 11:10:52 CST 2018
     */
    public Integer getChapterId() {
        return chapterId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_brother_chapter.chapter_id
     *
     * @param chapterId the value for t_brother_chapter.chapter_id
     *
     * @mbggenerated Mon Jul 23 11:10:52 CST 2018
     */
    public void setChapterId(Integer chapterId) {
        this.chapterId = chapterId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_brother_chapter.collect_flag
     *
     * @return the value of t_brother_chapter.collect_flag
     *
     * @mbggenerated Mon Jul 23 11:10:52 CST 2018
     */
    public Integer getCollectFlag() {
        return collectFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_brother_chapter.collect_flag
     *
     * @param collectFlag the value for t_brother_chapter.collect_flag
     *
     * @mbggenerated Mon Jul 23 11:10:52 CST 2018
     */
    public void setCollectFlag(Integer collectFlag) {
        this.collectFlag = collectFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_brother_chapter.update_time
     *
     * @return the value of t_brother_chapter.update_time
     *
     * @mbggenerated Mon Jul 23 11:10:52 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_brother_chapter.update_time
     *
     * @param updateTime the value for t_brother_chapter.update_time
     *
     * @mbggenerated Mon Jul 23 11:10:52 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}