package com.example.thymeleaf.model;

import java.util.Date;

public class Brother {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_brother.brother_id
     *
     * @mbggenerated Mon Jul 23 11:10:52 CST 2018
     */
    private Integer brotherId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_brother.article_id
     *
     * @mbggenerated Mon Jul 23 11:10:52 CST 2018
     */
    private Integer articleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_brother.brother_url
     *
     * @mbggenerated Mon Jul 23 11:10:52 CST 2018
     */
    private String brotherUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_brother.domain_id
     *
     * @mbggenerated Mon Jul 23 11:10:52 CST 2018
     */
    private Integer domainId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_brother.brother_score
     *
     * @mbggenerated Mon Jul 23 11:10:52 CST 2018
     */
    private Integer brotherScore;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_brother.create_time
     *
     * @mbggenerated Mon Jul 23 11:10:52 CST 2018
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_brother.update_turns
     *
     * @mbggenerated Mon Jul 23 11:10:52 CST 2018
     */
    private Integer updateTurns;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_brother.brother_id
     *
     * @return the value of t_brother.brother_id
     *
     * @mbggenerated Mon Jul 23 11:10:52 CST 2018
     */
    public Integer getBrotherId() {
        return brotherId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_brother.brother_id
     *
     * @param brotherId the value for t_brother.brother_id
     *
     * @mbggenerated Mon Jul 23 11:10:52 CST 2018
     */
    public void setBrotherId(Integer brotherId) {
        this.brotherId = brotherId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_brother.article_id
     *
     * @return the value of t_brother.article_id
     *
     * @mbggenerated Mon Jul 23 11:10:52 CST 2018
     */
    public Integer getArticleId() {
        return articleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_brother.article_id
     *
     * @param articleId the value for t_brother.article_id
     *
     * @mbggenerated Mon Jul 23 11:10:52 CST 2018
     */
    public void setArticleId(Integer articleId) {
        this.articleId = articleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_brother.brother_url
     *
     * @return the value of t_brother.brother_url
     *
     * @mbggenerated Mon Jul 23 11:10:52 CST 2018
     */
    public String getBrotherUrl() {
        return brotherUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_brother.brother_url
     *
     * @param brotherUrl the value for t_brother.brother_url
     *
     * @mbggenerated Mon Jul 23 11:10:52 CST 2018
     */
    public void setBrotherUrl(String brotherUrl) {
        this.brotherUrl = brotherUrl == null ? null : brotherUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_brother.domain_id
     *
     * @return the value of t_brother.domain_id
     *
     * @mbggenerated Mon Jul 23 11:10:52 CST 2018
     */
    public Integer getDomainId() {
        return domainId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_brother.domain_id
     *
     * @param domainId the value for t_brother.domain_id
     *
     * @mbggenerated Mon Jul 23 11:10:52 CST 2018
     */
    public void setDomainId(Integer domainId) {
        this.domainId = domainId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_brother.brother_score
     *
     * @return the value of t_brother.brother_score
     *
     * @mbggenerated Mon Jul 23 11:10:52 CST 2018
     */
    public Integer getBrotherScore() {
        return brotherScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_brother.brother_score
     *
     * @param brotherScore the value for t_brother.brother_score
     *
     * @mbggenerated Mon Jul 23 11:10:52 CST 2018
     */
    public void setBrotherScore(Integer brotherScore) {
        this.brotherScore = brotherScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_brother.create_time
     *
     * @return the value of t_brother.create_time
     *
     * @mbggenerated Mon Jul 23 11:10:52 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_brother.create_time
     *
     * @param createTime the value for t_brother.create_time
     *
     * @mbggenerated Mon Jul 23 11:10:52 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_brother.update_turns
     *
     * @return the value of t_brother.update_turns
     *
     * @mbggenerated Mon Jul 23 11:10:52 CST 2018
     */
    public Integer getUpdateTurns() {
        return updateTurns;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_brother.update_turns
     *
     * @param updateTurns the value for t_brother.update_turns
     *
     * @mbggenerated Mon Jul 23 11:10:52 CST 2018
     */
    public void setUpdateTurns(Integer updateTurns) {
        this.updateTurns = updateTurns;
    }
}