package com.example.thymeleaf.model;

import java.util.Date;

public class Chapter {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_chapter.id
     *
     * @mbggenerated Mon Jul 23 11:10:52 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_chapter.artile_id
     *
     * @mbggenerated Mon Jul 23 11:10:52 CST 2018
     */
    private Integer artileId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_chapter.seq_id
     *
     * @mbggenerated Mon Jul 23 11:10:52 CST 2018
     */
    private Integer seqId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_chapter.title
     *
     * @mbggenerated Mon Jul 23 11:10:52 CST 2018
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_chapter.url
     *
     * @mbggenerated Mon Jul 23 11:10:52 CST 2018
     */
    private String url;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_chapter.local_url
     *
     * @mbggenerated Mon Jul 23 11:10:52 CST 2018
     */
    private String localUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_chapter.collect_flag
     *
     * @mbggenerated Mon Jul 23 11:10:52 CST 2018
     */
    private Boolean collectFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_chapter.update_time
     *
     * @mbggenerated Mon Jul 23 11:10:52 CST 2018
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_chapter.id
     *
     * @return the value of t_chapter.id
     *
     * @mbggenerated Mon Jul 23 11:10:52 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_chapter.id
     *
     * @param id the value for t_chapter.id
     *
     * @mbggenerated Mon Jul 23 11:10:52 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_chapter.artile_id
     *
     * @return the value of t_chapter.artile_id
     *
     * @mbggenerated Mon Jul 23 11:10:52 CST 2018
     */
    public Integer getArtileId() {
        return artileId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_chapter.artile_id
     *
     * @param artileId the value for t_chapter.artile_id
     *
     * @mbggenerated Mon Jul 23 11:10:52 CST 2018
     */
    public void setArtileId(Integer artileId) {
        this.artileId = artileId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_chapter.seq_id
     *
     * @return the value of t_chapter.seq_id
     *
     * @mbggenerated Mon Jul 23 11:10:52 CST 2018
     */
    public Integer getSeqId() {
        return seqId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_chapter.seq_id
     *
     * @param seqId the value for t_chapter.seq_id
     *
     * @mbggenerated Mon Jul 23 11:10:52 CST 2018
     */
    public void setSeqId(Integer seqId) {
        this.seqId = seqId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_chapter.title
     *
     * @return the value of t_chapter.title
     *
     * @mbggenerated Mon Jul 23 11:10:52 CST 2018
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_chapter.title
     *
     * @param title the value for t_chapter.title
     *
     * @mbggenerated Mon Jul 23 11:10:52 CST 2018
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_chapter.url
     *
     * @return the value of t_chapter.url
     *
     * @mbggenerated Mon Jul 23 11:10:52 CST 2018
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_chapter.url
     *
     * @param url the value for t_chapter.url
     *
     * @mbggenerated Mon Jul 23 11:10:52 CST 2018
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_chapter.local_url
     *
     * @return the value of t_chapter.local_url
     *
     * @mbggenerated Mon Jul 23 11:10:52 CST 2018
     */
    public String getLocalUrl() {
        return localUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_chapter.local_url
     *
     * @param localUrl the value for t_chapter.local_url
     *
     * @mbggenerated Mon Jul 23 11:10:52 CST 2018
     */
    public void setLocalUrl(String localUrl) {
        this.localUrl = localUrl == null ? null : localUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_chapter.collect_flag
     *
     * @return the value of t_chapter.collect_flag
     *
     * @mbggenerated Mon Jul 23 11:10:52 CST 2018
     */
    public Boolean getCollectFlag() {
        return collectFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_chapter.collect_flag
     *
     * @param collectFlag the value for t_chapter.collect_flag
     *
     * @mbggenerated Mon Jul 23 11:10:52 CST 2018
     */
    public void setCollectFlag(Boolean collectFlag) {
        this.collectFlag = collectFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_chapter.update_time
     *
     * @return the value of t_chapter.update_time
     *
     * @mbggenerated Mon Jul 23 11:10:52 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_chapter.update_time
     *
     * @param updateTime the value for t_chapter.update_time
     *
     * @mbggenerated Mon Jul 23 11:10:52 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}