package com.example.thymeleaf.model;

import java.util.ArrayList;
import java.util.List;

public class DomainCssSelectorExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_domain_css_selector
     *
     * @mbggenerated Fri Nov 30 18:44:53 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_domain_css_selector
     *
     * @mbggenerated Fri Nov 30 18:44:53 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_domain_css_selector
     *
     * @mbggenerated Fri Nov 30 18:44:53 CST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_domain_css_selector
     *
     * @mbggenerated Fri Nov 30 18:44:53 CST 2018
     */
    public DomainCssSelectorExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_domain_css_selector
     *
     * @mbggenerated Fri Nov 30 18:44:53 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_domain_css_selector
     *
     * @mbggenerated Fri Nov 30 18:44:53 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_domain_css_selector
     *
     * @mbggenerated Fri Nov 30 18:44:53 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_domain_css_selector
     *
     * @mbggenerated Fri Nov 30 18:44:53 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_domain_css_selector
     *
     * @mbggenerated Fri Nov 30 18:44:53 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_domain_css_selector
     *
     * @mbggenerated Fri Nov 30 18:44:53 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_domain_css_selector
     *
     * @mbggenerated Fri Nov 30 18:44:53 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_domain_css_selector
     *
     * @mbggenerated Fri Nov 30 18:44:53 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_domain_css_selector
     *
     * @mbggenerated Fri Nov 30 18:44:53 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_domain_css_selector
     *
     * @mbggenerated Fri Nov 30 18:44:53 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_domain_css_selector
     *
     * @mbggenerated Fri Nov 30 18:44:53 CST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andDomainIdIsNull() {
            addCriterion("domain_id is null");
            return (Criteria) this;
        }

        public Criteria andDomainIdIsNotNull() {
            addCriterion("domain_id is not null");
            return (Criteria) this;
        }

        public Criteria andDomainIdEqualTo(Integer value) {
            addCriterion("domain_id =", value, "domainId");
            return (Criteria) this;
        }

        public Criteria andDomainIdNotEqualTo(Integer value) {
            addCriterion("domain_id <>", value, "domainId");
            return (Criteria) this;
        }

        public Criteria andDomainIdGreaterThan(Integer value) {
            addCriterion("domain_id >", value, "domainId");
            return (Criteria) this;
        }

        public Criteria andDomainIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("domain_id >=", value, "domainId");
            return (Criteria) this;
        }

        public Criteria andDomainIdLessThan(Integer value) {
            addCriterion("domain_id <", value, "domainId");
            return (Criteria) this;
        }

        public Criteria andDomainIdLessThanOrEqualTo(Integer value) {
            addCriterion("domain_id <=", value, "domainId");
            return (Criteria) this;
        }

        public Criteria andDomainIdIn(List<Integer> values) {
            addCriterion("domain_id in", values, "domainId");
            return (Criteria) this;
        }

        public Criteria andDomainIdNotIn(List<Integer> values) {
            addCriterion("domain_id not in", values, "domainId");
            return (Criteria) this;
        }

        public Criteria andDomainIdBetween(Integer value1, Integer value2) {
            addCriterion("domain_id between", value1, value2, "domainId");
            return (Criteria) this;
        }

        public Criteria andDomainIdNotBetween(Integer value1, Integer value2) {
            addCriterion("domain_id not between", value1, value2, "domainId");
            return (Criteria) this;
        }

        public Criteria andLevel1SelectorIsNull() {
            addCriterion("level1_selector is null");
            return (Criteria) this;
        }

        public Criteria andLevel1SelectorIsNotNull() {
            addCriterion("level1_selector is not null");
            return (Criteria) this;
        }

        public Criteria andLevel1SelectorEqualTo(String value) {
            addCriterion("level1_selector =", value, "level1Selector");
            return (Criteria) this;
        }

        public Criteria andLevel1SelectorNotEqualTo(String value) {
            addCriterion("level1_selector <>", value, "level1Selector");
            return (Criteria) this;
        }

        public Criteria andLevel1SelectorGreaterThan(String value) {
            addCriterion("level1_selector >", value, "level1Selector");
            return (Criteria) this;
        }

        public Criteria andLevel1SelectorGreaterThanOrEqualTo(String value) {
            addCriterion("level1_selector >=", value, "level1Selector");
            return (Criteria) this;
        }

        public Criteria andLevel1SelectorLessThan(String value) {
            addCriterion("level1_selector <", value, "level1Selector");
            return (Criteria) this;
        }

        public Criteria andLevel1SelectorLessThanOrEqualTo(String value) {
            addCriterion("level1_selector <=", value, "level1Selector");
            return (Criteria) this;
        }

        public Criteria andLevel1SelectorLike(String value) {
            addCriterion("level1_selector like", value, "level1Selector");
            return (Criteria) this;
        }

        public Criteria andLevel1SelectorNotLike(String value) {
            addCriterion("level1_selector not like", value, "level1Selector");
            return (Criteria) this;
        }

        public Criteria andLevel1SelectorIn(List<String> values) {
            addCriterion("level1_selector in", values, "level1Selector");
            return (Criteria) this;
        }

        public Criteria andLevel1SelectorNotIn(List<String> values) {
            addCriterion("level1_selector not in", values, "level1Selector");
            return (Criteria) this;
        }

        public Criteria andLevel1SelectorBetween(String value1, String value2) {
            addCriterion("level1_selector between", value1, value2, "level1Selector");
            return (Criteria) this;
        }

        public Criteria andLevel1SelectorNotBetween(String value1, String value2) {
            addCriterion("level1_selector not between", value1, value2, "level1Selector");
            return (Criteria) this;
        }

        public Criteria andLevel2SelectorIsNull() {
            addCriterion("level2_selector is null");
            return (Criteria) this;
        }

        public Criteria andLevel2SelectorIsNotNull() {
            addCriterion("level2_selector is not null");
            return (Criteria) this;
        }

        public Criteria andLevel2SelectorEqualTo(String value) {
            addCriterion("level2_selector =", value, "level2Selector");
            return (Criteria) this;
        }

        public Criteria andLevel2SelectorNotEqualTo(String value) {
            addCriterion("level2_selector <>", value, "level2Selector");
            return (Criteria) this;
        }

        public Criteria andLevel2SelectorGreaterThan(String value) {
            addCriterion("level2_selector >", value, "level2Selector");
            return (Criteria) this;
        }

        public Criteria andLevel2SelectorGreaterThanOrEqualTo(String value) {
            addCriterion("level2_selector >=", value, "level2Selector");
            return (Criteria) this;
        }

        public Criteria andLevel2SelectorLessThan(String value) {
            addCriterion("level2_selector <", value, "level2Selector");
            return (Criteria) this;
        }

        public Criteria andLevel2SelectorLessThanOrEqualTo(String value) {
            addCriterion("level2_selector <=", value, "level2Selector");
            return (Criteria) this;
        }

        public Criteria andLevel2SelectorLike(String value) {
            addCriterion("level2_selector like", value, "level2Selector");
            return (Criteria) this;
        }

        public Criteria andLevel2SelectorNotLike(String value) {
            addCriterion("level2_selector not like", value, "level2Selector");
            return (Criteria) this;
        }

        public Criteria andLevel2SelectorIn(List<String> values) {
            addCriterion("level2_selector in", values, "level2Selector");
            return (Criteria) this;
        }

        public Criteria andLevel2SelectorNotIn(List<String> values) {
            addCriterion("level2_selector not in", values, "level2Selector");
            return (Criteria) this;
        }

        public Criteria andLevel2SelectorBetween(String value1, String value2) {
            addCriterion("level2_selector between", value1, value2, "level2Selector");
            return (Criteria) this;
        }

        public Criteria andLevel2SelectorNotBetween(String value1, String value2) {
            addCriterion("level2_selector not between", value1, value2, "level2Selector");
            return (Criteria) this;
        }

        public Criteria andLevel3SelectorIsNull() {
            addCriterion("level3_selector is null");
            return (Criteria) this;
        }

        public Criteria andLevel3SelectorIsNotNull() {
            addCriterion("level3_selector is not null");
            return (Criteria) this;
        }

        public Criteria andLevel3SelectorEqualTo(String value) {
            addCriterion("level3_selector =", value, "level3Selector");
            return (Criteria) this;
        }

        public Criteria andLevel3SelectorNotEqualTo(String value) {
            addCriterion("level3_selector <>", value, "level3Selector");
            return (Criteria) this;
        }

        public Criteria andLevel3SelectorGreaterThan(String value) {
            addCriterion("level3_selector >", value, "level3Selector");
            return (Criteria) this;
        }

        public Criteria andLevel3SelectorGreaterThanOrEqualTo(String value) {
            addCriterion("level3_selector >=", value, "level3Selector");
            return (Criteria) this;
        }

        public Criteria andLevel3SelectorLessThan(String value) {
            addCriterion("level3_selector <", value, "level3Selector");
            return (Criteria) this;
        }

        public Criteria andLevel3SelectorLessThanOrEqualTo(String value) {
            addCriterion("level3_selector <=", value, "level3Selector");
            return (Criteria) this;
        }

        public Criteria andLevel3SelectorLike(String value) {
            addCriterion("level3_selector like", value, "level3Selector");
            return (Criteria) this;
        }

        public Criteria andLevel3SelectorNotLike(String value) {
            addCriterion("level3_selector not like", value, "level3Selector");
            return (Criteria) this;
        }

        public Criteria andLevel3SelectorIn(List<String> values) {
            addCriterion("level3_selector in", values, "level3Selector");
            return (Criteria) this;
        }

        public Criteria andLevel3SelectorNotIn(List<String> values) {
            addCriterion("level3_selector not in", values, "level3Selector");
            return (Criteria) this;
        }

        public Criteria andLevel3SelectorBetween(String value1, String value2) {
            addCriterion("level3_selector between", value1, value2, "level3Selector");
            return (Criteria) this;
        }

        public Criteria andLevel3SelectorNotBetween(String value1, String value2) {
            addCriterion("level3_selector not between", value1, value2, "level3Selector");
            return (Criteria) this;
        }

        public Criteria andExtraRuleIsNull() {
            addCriterion("extra_rule is null");
            return (Criteria) this;
        }

        public Criteria andExtraRuleIsNotNull() {
            addCriterion("extra_rule is not null");
            return (Criteria) this;
        }

        public Criteria andExtraRuleEqualTo(String value) {
            addCriterion("extra_rule =", value, "extraRule");
            return (Criteria) this;
        }

        public Criteria andExtraRuleNotEqualTo(String value) {
            addCriterion("extra_rule <>", value, "extraRule");
            return (Criteria) this;
        }

        public Criteria andExtraRuleGreaterThan(String value) {
            addCriterion("extra_rule >", value, "extraRule");
            return (Criteria) this;
        }

        public Criteria andExtraRuleGreaterThanOrEqualTo(String value) {
            addCriterion("extra_rule >=", value, "extraRule");
            return (Criteria) this;
        }

        public Criteria andExtraRuleLessThan(String value) {
            addCriterion("extra_rule <", value, "extraRule");
            return (Criteria) this;
        }

        public Criteria andExtraRuleLessThanOrEqualTo(String value) {
            addCriterion("extra_rule <=", value, "extraRule");
            return (Criteria) this;
        }

        public Criteria andExtraRuleLike(String value) {
            addCriterion("extra_rule like", value, "extraRule");
            return (Criteria) this;
        }

        public Criteria andExtraRuleNotLike(String value) {
            addCriterion("extra_rule not like", value, "extraRule");
            return (Criteria) this;
        }

        public Criteria andExtraRuleIn(List<String> values) {
            addCriterion("extra_rule in", values, "extraRule");
            return (Criteria) this;
        }

        public Criteria andExtraRuleNotIn(List<String> values) {
            addCriterion("extra_rule not in", values, "extraRule");
            return (Criteria) this;
        }

        public Criteria andExtraRuleBetween(String value1, String value2) {
            addCriterion("extra_rule between", value1, value2, "extraRule");
            return (Criteria) this;
        }

        public Criteria andExtraRuleNotBetween(String value1, String value2) {
            addCriterion("extra_rule not between", value1, value2, "extraRule");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_domain_css_selector
     *
     * @mbggenerated do_not_delete_during_merge Fri Nov 30 18:44:53 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_domain_css_selector
     *
     * @mbggenerated Fri Nov 30 18:44:53 CST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}