package com.example.thymeleaf.model;

public class DomainCssSelector {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_domain_css_selector.id
     *
     * @mbggenerated Fri Nov 30 18:44:53 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_domain_css_selector.domain_id
     *
     * @mbggenerated Fri Nov 30 18:44:53 CST 2018
     */
    private Integer domainId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_domain_css_selector.level1_selector
     *
     * @mbggenerated Fri Nov 30 18:44:53 CST 2018
     */
    private String level1Selector;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_domain_css_selector.level2_selector
     *
     * @mbggenerated Fri Nov 30 18:44:53 CST 2018
     */
    private String level2Selector;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_domain_css_selector.level3_selector
     *
     * @mbggenerated Fri Nov 30 18:44:53 CST 2018
     */
    private String level3Selector;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_domain_css_selector.extra_rule
     *
     * @mbggenerated Fri Nov 30 18:44:53 CST 2018
     */
    private String extraRule;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_domain_css_selector.id
     *
     * @return the value of t_domain_css_selector.id
     *
     * @mbggenerated Fri Nov 30 18:44:53 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_domain_css_selector.id
     *
     * @param id the value for t_domain_css_selector.id
     *
     * @mbggenerated Fri Nov 30 18:44:53 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_domain_css_selector.domain_id
     *
     * @return the value of t_domain_css_selector.domain_id
     *
     * @mbggenerated Fri Nov 30 18:44:53 CST 2018
     */
    public Integer getDomainId() {
        return domainId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_domain_css_selector.domain_id
     *
     * @param domainId the value for t_domain_css_selector.domain_id
     *
     * @mbggenerated Fri Nov 30 18:44:53 CST 2018
     */
    public void setDomainId(Integer domainId) {
        this.domainId = domainId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_domain_css_selector.level1_selector
     *
     * @return the value of t_domain_css_selector.level1_selector
     *
     * @mbggenerated Fri Nov 30 18:44:53 CST 2018
     */
    public String getLevel1Selector() {
        return level1Selector;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_domain_css_selector.level1_selector
     *
     * @param level1Selector the value for t_domain_css_selector.level1_selector
     *
     * @mbggenerated Fri Nov 30 18:44:53 CST 2018
     */
    public void setLevel1Selector(String level1Selector) {
        this.level1Selector = level1Selector == null ? null : level1Selector.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_domain_css_selector.level2_selector
     *
     * @return the value of t_domain_css_selector.level2_selector
     *
     * @mbggenerated Fri Nov 30 18:44:53 CST 2018
     */
    public String getLevel2Selector() {
        return level2Selector;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_domain_css_selector.level2_selector
     *
     * @param level2Selector the value for t_domain_css_selector.level2_selector
     *
     * @mbggenerated Fri Nov 30 18:44:53 CST 2018
     */
    public void setLevel2Selector(String level2Selector) {
        this.level2Selector = level2Selector == null ? null : level2Selector.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_domain_css_selector.level3_selector
     *
     * @return the value of t_domain_css_selector.level3_selector
     *
     * @mbggenerated Fri Nov 30 18:44:53 CST 2018
     */
    public String getLevel3Selector() {
        return level3Selector;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_domain_css_selector.level3_selector
     *
     * @param level3Selector the value for t_domain_css_selector.level3_selector
     *
     * @mbggenerated Fri Nov 30 18:44:53 CST 2018
     */
    public void setLevel3Selector(String level3Selector) {
        this.level3Selector = level3Selector == null ? null : level3Selector.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_domain_css_selector.extra_rule
     *
     * @return the value of t_domain_css_selector.extra_rule
     *
     * @mbggenerated Fri Nov 30 18:44:53 CST 2018
     */
    public String getExtraRule() {
        return extraRule;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_domain_css_selector.extra_rule
     *
     * @param extraRule the value for t_domain_css_selector.extra_rule
     *
     * @mbggenerated Fri Nov 30 18:44:53 CST 2018
     */
    public void setExtraRule(String extraRule) {
        this.extraRule = extraRule == null ? null : extraRule.trim();
    }
}