package com.example.thymeleaf.model;

import java.util.Date;

public class ScheduleTask {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_schedule_task.id
     *
     * @mbggenerated Mon Jul 23 11:10:52 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_schedule_task.bean_name
     *
     * @mbggenerated Mon Jul 23 11:10:52 CST 2018
     */
    private String beanName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_schedule_task.bean_method
     *
     * @mbggenerated Mon Jul 23 11:10:52 CST 2018
     */
    private String beanMethod;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_schedule_task.last_update
     *
     * @mbggenerated Mon Jul 23 11:10:52 CST 2018
     */
    private Date lastUpdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_schedule_task.fix_delay
     *
     * @mbggenerated Mon Jul 23 11:10:52 CST 2018
     */
    private Integer fixDelay;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_schedule_task.enable
     *
     * @mbggenerated Mon Jul 23 11:10:52 CST 2018
     */
    private Boolean enable;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_schedule_task.id
     *
     * @return the value of t_schedule_task.id
     *
     * @mbggenerated Mon Jul 23 11:10:52 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_schedule_task.id
     *
     * @param id the value for t_schedule_task.id
     *
     * @mbggenerated Mon Jul 23 11:10:52 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_schedule_task.bean_name
     *
     * @return the value of t_schedule_task.bean_name
     *
     * @mbggenerated Mon Jul 23 11:10:52 CST 2018
     */
    public String getBeanName() {
        return beanName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_schedule_task.bean_name
     *
     * @param beanName the value for t_schedule_task.bean_name
     *
     * @mbggenerated Mon Jul 23 11:10:52 CST 2018
     */
    public void setBeanName(String beanName) {
        this.beanName = beanName == null ? null : beanName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_schedule_task.bean_method
     *
     * @return the value of t_schedule_task.bean_method
     *
     * @mbggenerated Mon Jul 23 11:10:52 CST 2018
     */
    public String getBeanMethod() {
        return beanMethod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_schedule_task.bean_method
     *
     * @param beanMethod the value for t_schedule_task.bean_method
     *
     * @mbggenerated Mon Jul 23 11:10:52 CST 2018
     */
    public void setBeanMethod(String beanMethod) {
        this.beanMethod = beanMethod == null ? null : beanMethod.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_schedule_task.last_update
     *
     * @return the value of t_schedule_task.last_update
     *
     * @mbggenerated Mon Jul 23 11:10:52 CST 2018
     */
    public Date getLastUpdate() {
        return lastUpdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_schedule_task.last_update
     *
     * @param lastUpdate the value for t_schedule_task.last_update
     *
     * @mbggenerated Mon Jul 23 11:10:52 CST 2018
     */
    public void setLastUpdate(Date lastUpdate) {
        this.lastUpdate = lastUpdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_schedule_task.fix_delay
     *
     * @return the value of t_schedule_task.fix_delay
     *
     * @mbggenerated Mon Jul 23 11:10:52 CST 2018
     */
    public Integer getFixDelay() {
        return fixDelay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_schedule_task.fix_delay
     *
     * @param fixDelay the value for t_schedule_task.fix_delay
     *
     * @mbggenerated Mon Jul 23 11:10:52 CST 2018
     */
    public void setFixDelay(Integer fixDelay) {
        this.fixDelay = fixDelay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_schedule_task.enable
     *
     * @return the value of t_schedule_task.enable
     *
     * @mbggenerated Mon Jul 23 11:10:52 CST 2018
     */
    public Boolean getEnable() {
        return enable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_schedule_task.enable
     *
     * @param enable the value for t_schedule_task.enable
     *
     * @mbggenerated Mon Jul 23 11:10:52 CST 2018
     */
    public void setEnable(Boolean enable) {
        this.enable = enable;
    }
}