package com.example.thymeleaf.model;

public class Seed {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_seeds.id
     *
     * @mbggenerated Fri Jun 29 19:09:55 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_seeds.url
     *
     * @mbggenerated Fri Jun 29 19:09:55 CST 2018
     */
    private String url;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_seeds.category_id
     *
     * @mbggenerated Fri Jun 29 19:09:55 CST 2018
     */
    private Byte categoryId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_seeds.modify_date
     *
     * @mbggenerated Fri Jun 29 19:09:55 CST 2018
     */
    private String modifyDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_seeds.parse_class
     *
     * @mbggenerated Fri Jun 29 19:09:55 CST 2018
     */
    private String parseClass;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_seeds.id
     *
     * @return the value of t_seeds.id
     *
     * @mbggenerated Fri Jun 29 19:09:55 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_seeds.id
     *
     * @param id the value for t_seeds.id
     *
     * @mbggenerated Fri Jun 29 19:09:55 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_seeds.url
     *
     * @return the value of t_seeds.url
     *
     * @mbggenerated Fri Jun 29 19:09:55 CST 2018
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_seeds.url
     *
     * @param url the value for t_seeds.url
     *
     * @mbggenerated Fri Jun 29 19:09:55 CST 2018
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_seeds.category_id
     *
     * @return the value of t_seeds.category_id
     *
     * @mbggenerated Fri Jun 29 19:09:55 CST 2018
     */
    public Byte getCategoryId() {
        return categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_seeds.category_id
     *
     * @param categoryId the value for t_seeds.category_id
     *
     * @mbggenerated Fri Jun 29 19:09:55 CST 2018
     */
    public void setCategoryId(Byte categoryId) {
        this.categoryId = categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_seeds.modify_date
     *
     * @return the value of t_seeds.modify_date
     *
     * @mbggenerated Fri Jun 29 19:09:55 CST 2018
     */
    public String getModifyDate() {
        return modifyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_seeds.modify_date
     *
     * @param modifyDate the value for t_seeds.modify_date
     *
     * @mbggenerated Fri Jun 29 19:09:55 CST 2018
     */
    public void setModifyDate(String modifyDate) {
        this.modifyDate = modifyDate == null ? null : modifyDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_seeds.parse_class
     *
     * @return the value of t_seeds.parse_class
     *
     * @mbggenerated Fri Jun 29 19:09:55 CST 2018
     */
    public String getParseClass() {
        return parseClass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_seeds.parse_class
     *
     * @param parseClass the value for t_seeds.parse_class
     *
     * @mbggenerated Fri Jun 29 19:09:55 CST 2018
     */
    public void setParseClass(String parseClass) {
        this.parseClass = parseClass == null ? null : parseClass.trim();
    }
}