package com.example.thymeleaf.model;

import java.util.Date;

public class WooniuSynId {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_wooniu_syn_ids.id
     *
     * @mbggenerated Fri Nov 30 18:44:53 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_wooniu_syn_ids.article_id
     *
     * @mbggenerated Fri Nov 30 18:44:53 CST 2018
     */
    private Integer articleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_wooniu_syn_ids.status
     *
     * @mbggenerated Fri Nov 30 18:44:53 CST 2018
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_wooniu_syn_ids.pos
     *
     * @mbggenerated Fri Nov 30 18:44:53 CST 2018
     */
    private Integer pos;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_wooniu_syn_ids.create_time
     *
     * @mbggenerated Fri Nov 30 18:44:53 CST 2018
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_wooniu_syn_ids.id
     *
     * @return the value of t_wooniu_syn_ids.id
     *
     * @mbggenerated Fri Nov 30 18:44:53 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_wooniu_syn_ids.id
     *
     * @param id the value for t_wooniu_syn_ids.id
     *
     * @mbggenerated Fri Nov 30 18:44:53 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_wooniu_syn_ids.article_id
     *
     * @return the value of t_wooniu_syn_ids.article_id
     *
     * @mbggenerated Fri Nov 30 18:44:53 CST 2018
     */
    public Integer getArticleId() {
        return articleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_wooniu_syn_ids.article_id
     *
     * @param articleId the value for t_wooniu_syn_ids.article_id
     *
     * @mbggenerated Fri Nov 30 18:44:53 CST 2018
     */
    public void setArticleId(Integer articleId) {
        this.articleId = articleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_wooniu_syn_ids.status
     *
     * @return the value of t_wooniu_syn_ids.status
     *
     * @mbggenerated Fri Nov 30 18:44:53 CST 2018
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_wooniu_syn_ids.status
     *
     * @param status the value for t_wooniu_syn_ids.status
     *
     * @mbggenerated Fri Nov 30 18:44:53 CST 2018
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_wooniu_syn_ids.pos
     *
     * @return the value of t_wooniu_syn_ids.pos
     *
     * @mbggenerated Fri Nov 30 18:44:53 CST 2018
     */
    public Integer getPos() {
        return pos;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_wooniu_syn_ids.pos
     *
     * @param pos the value for t_wooniu_syn_ids.pos
     *
     * @mbggenerated Fri Nov 30 18:44:53 CST 2018
     */
    public void setPos(Integer pos) {
        this.pos = pos;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_wooniu_syn_ids.create_time
     *
     * @return the value of t_wooniu_syn_ids.create_time
     *
     * @mbggenerated Fri Nov 30 18:44:53 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_wooniu_syn_ids.create_time
     *
     * @param createTime the value for t_wooniu_syn_ids.create_time
     *
     * @mbggenerated Fri Nov 30 18:44:53 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}